# Site
name: 'Deadline Calculators'
description: 'Simplify the process of calculating and managing trial deadlines.'
logo: 'assets/images/logo.webp'
favicon: 'assets/images/favicon.ico'
baseurl: ''
email: 'info@deadlinecalculators.com'

include: ["_pages"]

# permalink: /blog/:title/
permalink: /blog/:year/:month/:day/:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
  deadline_calculators:
    name:           Deadline Calculators
    site:           https://deadlinecalculators.com
    avatar:         assets/images/avatar1.webp
    bio:            "Simplify the process of calculating and managing trial deadlines."
    email:          info@deadlinecalculators.com
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: deadline_calculators
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, node_modules]